app:
  env: dev
http:
  port: 8000
  host: localhost
  http_enabled: false
database:
  user: nKPb8UwIZdl222S2RyZVI0C1zieT5ahN5JZ1fodX2QA=
  password: gdPM2TlqG3BPx7-8CQ5lekHkIBQprdtCIub7j722YSM=
  host: localhost
  database: ws