version: "3.7"

services:
  ws-postgresql:
    image: postgres:14
    container_name: webstudio-postgresql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        aliases:
          - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webs

  ws-server:
    container_name: web-studio-app
    restart: on-failure
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    networks:
      - default
    depends_on:
      - ws-postgresql
    environment:
      - ENV=dev
    ports:
      - "3000:3000"

volumes:
  pg_data:

networks:
  default:
    driver: bridge